### PR TITLE
Setup grid and row and column functions, while also adding query selectors and event listeners to buttons that will be created

### PR DESCRIPTION
**Pull request by johnzhou1210**

### CODE REVIEW

**Comment by johnzhou1210** [comment]
pls approve

**Review by jennydevs — APPROVED** [review]
Looks fine to me, tested the changes and there are indeed rows and columns being added. Resetting the grid and adding back rows and columns works as well.

**Comment by jennydevs** [comment]
Also there's no notifications apparently showing up anywhere unless you subscribe to a pull request, so I didn't see this sooner. Send a message in the discord to notify for pull request reviews.

**Comment by MichaelLally** [comment]
> Also there's no notifications apparently showing up anywhere unless you subscribe to a pull request, so I didn't see this sooner. Send a message in the discord to notify for pull request reviews.

@jennyton88 @johnzhou1210 When you open a PR, you can assign reviewers, which will should send an email notification (depending on your notification settings)

**Pull request merged**
